# SPDX-FileCopyrightText: © 2025 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

style_edition = "2024"
newline_style = "Unix"
tab_spaces = 2
