# SPDX-FileCopyrightText: © 2025 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-project-template"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-project-template"

[[annotations]]
path = "src/fonts/SourceCodePro-**"
SPDX-FileCopyrightText = "© 2010, 2012 Adobe Systems Incorporated (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "src/fonts/SourceSans3-**"
SPDX-FileCopyrightText = "© 2010-2020 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "src/fonts/SourceSerif4-**"
SPDX-FileCopyrightText = "© 2014 - 2023 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"
