# SPDX-FileCopyrightText: © 2025 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids-project-template"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids-project-template"

[[annotations]]
path = "OSSMETADATA"
SPDX-FileCopyrightText = "© 2025 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "**.xcodeproj/**",
  "**/Assets.xcassets/**",
  "**/Preview Content/**",
]
SPDX-FileCopyrightText = "© 2025 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/src/docs/asciidoc/c4/container/_includes/**.adoc"
SPDX-FileCopyrightText = "© 2025 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/src/docs/asciidoc/docinfo/*.html"
SPDX-FileCopyrightText = "© 2025 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/src/docs/asciidoc/css/font-awesome.css"
SPDX-FileCopyrightText = "© 2012 Dave Gandy (http://fontawesome.io)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docs/src/docs/asciidoc/fonts/fontawesome-webfont-4.7.0.woff2"
SPDX-FileCopyrightText = "© 2012 Dave Gandy (http://fontawesome.io)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/src/docs/asciidoc/fonts/MPlus1mn-**"
SPDX-FileCopyrightText = "© 2002-2019 The M+ FONTS Project Authors"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/src/docs/asciidoc/fonts/NotoEmoji-Regular.ttf"
SPDX-FileCopyrightText = "© 2013 Google LLC"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/src/docs/asciidoc/fonts/SourceCodePro-**"
SPDX-FileCopyrightText = "© 2010, 2012 Adobe Systems Incorporated (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/src/docs/asciidoc/fonts/SourceSans3-**"
SPDX-FileCopyrightText = "© 2010-2020 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "docs/src/docs/asciidoc/fonts/SourceSerif4-**"
SPDX-FileCopyrightText = "© 2014 - 2023 Adobe (http://www.adobe.com/)"
SPDX-License-Identifier = "OFL-1.1"
