# SPDX-FileCopyrightText: © 2025 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "stable-2025-06-26"
components = ["clippy", "rustfmt"]
profile = "minimal"
